# Generated by Django 2.2.4 on 2019-10-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_auto_20191029_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['mark']},
        ),
    ]
