# Generated by Django 2.2.4 on 2019-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_auto_20191029_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.IntegerField(),
        ),
    ]
