# Generated by Django 2.2.4 on 2019-10-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_auto_20191029_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-mark']},
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=8),
        ),
    ]
